[Settings]

ID = "wai-intro-wcag"

[build]

command = "bundle exec jekyll build --config '_config.yml,_config_staging.yml'"
publish = "_site"

[[redirects]]
  from = "/"
  to = "/standards-guidelines/wcag/"