[build]
command = "git submodule update --init --remote && bundle exec jekyll build --config '_config.yml,_config_staging.yml'"
publish = "_site"

[build.environment]
RUBY_VERSION = "2.6.2" 

[[redirects]]
  from = "/"
  to = "/standards-guidelines/wcag/"

[dev]
publish = "_site"
framework = "#static"
